on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is draft
        if: github.event.pull_request.draft == false
        run: echo "This PR is not a draft"